management.endpoints.web.exposure.include: "*"
server.error.whitelabel.enabled: false


uno:
  korean:
    hello: 안녕하세요
  english:
    hello: hello

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  thymeleaf3.decoupled-logic: true
