management.endpoints.web.exposure.include: "*"
server.error.whitelabel.enabled: false

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace

uno:
  korean:
    hello: 안녕하세요
  english:
    hello: hello

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  thymeleaf3.decoupled-logic: true
